PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS sources(id INTEGER PRIMARY KEY,name TEXT UNIQUE,url TEXT,source_type TEXT,checked_at TEXT,notes TEXT);
CREATE TABLE IF NOT EXISTS seasons(id INTEGER PRIMARY KEY,season INTEGER NOT NULL,phase TEXT NOT NULL DEFAULT 'regular',league TEXT,start_date TEXT,end_date TEXT,UNIQUE(season,phase,league));
CREATE TABLE IF NOT EXISTS teams(id INTEGER PRIMARY KEY,team_code TEXT UNIQUE,team_name TEXT NOT NULL,canonical_name TEXT,league TEXT,valid_from INTEGER,valid_to INTEGER,notes TEXT);
CREATE TABLE IF NOT EXISTS team_aliases(id INTEGER PRIMARY KEY,team_id INTEGER NOT NULL,alias TEXT NOT NULL,valid_from INTEGER,valid_to INTEGER,UNIQUE(team_id,alias),FOREIGN KEY(team_id) REFERENCES teams(id));
CREATE TABLE IF NOT EXISTS players(id INTEGER PRIMARY KEY,player_code TEXT UNIQUE,name TEXT NOT NULL,name_kana TEXT,birth_date TEXT,position TEXT,bats TEXT,throws TEXT,debut_date TEXT,retirement_date TEXT,source_url TEXT);
CREATE TABLE IF NOT EXISTS player_aliases(id INTEGER PRIMARY KEY,player_id INTEGER NOT NULL,alias TEXT NOT NULL,UNIQUE(player_id,alias),FOREIGN KEY(player_id) REFERENCES players(id));
CREATE TABLE IF NOT EXISTS player_team_history(id INTEGER PRIMARY KEY,player_id INTEGER NOT NULL,team_id INTEGER NOT NULL,season INTEGER,from_date TEXT,to_date TEXT,jersey_no TEXT,FOREIGN KEY(player_id) REFERENCES players(id),FOREIGN KEY(team_id) REFERENCES teams(id));
CREATE TABLE IF NOT EXISTS games(id INTEGER PRIMARY KEY,source_game_id TEXT,game_date TEXT,season INTEGER,phase TEXT,competition TEXT,league TEXT,home_team_id INTEGER,away_team_id INTEGER,home_score INTEGER,away_score INTEGER,innings INTEGER,venue TEXT,attendance INTEGER,winning_pitcher_id INTEGER,losing_pitcher_id INTEGER,save_pitcher_id INTEGER,is_extra_innings INTEGER DEFAULT 0,is_no_hitter INTEGER DEFAULT 0,is_perfect_game INTEGER DEFAULT 0,notes TEXT,source_url TEXT,UNIQUE(source_game_id,source_url));
CREATE TABLE IF NOT EXISTS game_events(id INTEGER PRIMARY KEY,game_id INTEGER NOT NULL,inning INTEGER,half TEXT,outs_before INTEGER,batter_id INTEGER,pitcher_id INTEGER,event_type TEXT,event_text TEXT,rbi INTEGER,runs_scored INTEGER,FOREIGN KEY(game_id) REFERENCES games(id),FOREIGN KEY(batter_id) REFERENCES players(id),FOREIGN KEY(pitcher_id) REFERENCES players(id));
CREATE TABLE IF NOT EXISTS batting_game(id INTEGER PRIMARY KEY,game_id INTEGER,player_id INTEGER,team_id INTEGER,batting_order INTEGER,plate_appearances INTEGER,at_bats INTEGER,runs INTEGER,hits INTEGER,doubles INTEGER,triples INTEGER,home_runs INTEGER,rbi INTEGER,walks INTEGER,hit_by_pitch INTEGER,strikeouts INTEGER,stolen_bases INTEGER,caught_stealing INTEGER,UNIQUE(game_id,player_id));
CREATE TABLE IF NOT EXISTS pitching_game(id INTEGER PRIMARY KEY,game_id INTEGER,player_id INTEGER,team_id INTEGER,innings_pitched REAL,batters_faced INTEGER,hits_allowed INTEGER,runs_allowed INTEGER,earned_runs INTEGER,walks INTEGER,strikeouts INTEGER,home_runs_allowed INTEGER,pitch_count INTEGER,UNIQUE(game_id,player_id));
CREATE TABLE IF NOT EXISTS player_season_batting(id INTEGER PRIMARY KEY,season INTEGER,player_id INTEGER,team_id INTEGER,games INTEGER,plate_appearances INTEGER,at_bats INTEGER,runs INTEGER,hits INTEGER,doubles INTEGER,triples INTEGER,home_runs INTEGER,rbi INTEGER,stolen_bases INTEGER,walks INTEGER,strikeouts INTEGER,batting_average REAL,obp REAL,slg REAL,ops REAL,UNIQUE(season,player_id,team_id));
CREATE TABLE IF NOT EXISTS player_season_pitching(id INTEGER PRIMARY KEY,season INTEGER,player_id INTEGER,team_id INTEGER,games INTEGER,wins INTEGER,losses INTEGER,saves INTEGER,holds INTEGER,innings_pitched REAL,hits_allowed INTEGER,runs_allowed INTEGER,earned_runs INTEGER,walks INTEGER,strikeouts INTEGER,home_runs_allowed INTEGER,era REAL,whip REAL,UNIQUE(season,player_id,team_id));
CREATE TABLE IF NOT EXISTS team_season_batting(id INTEGER PRIMARY KEY,season INTEGER,team_id INTEGER,games INTEGER,batting_average REAL,runs INTEGER,hits INTEGER,home_runs INTEGER,rbi INTEGER,stolen_bases INTEGER,UNIQUE(season,team_id));
CREATE TABLE IF NOT EXISTS team_season_pitching(id INTEGER PRIMARY KEY,season INTEGER,team_id INTEGER,games INTEGER,wins INTEGER,losses INTEGER,ties INTEGER,era REAL,runs_allowed INTEGER,strikeouts INTEGER,UNIQUE(season,team_id));
CREATE TABLE IF NOT EXISTS standings(id INTEGER PRIMARY KEY,season INTEGER,league TEXT,team_id INTEGER,games INTEGER,wins INTEGER,losses INTEGER,ties INTEGER,win_pct REAL,rank INTEGER,games_behind REAL,UNIQUE(season,league,team_id));
CREATE TABLE IF NOT EXISTS awards(id INTEGER PRIMARY KEY,season INTEGER,award_type TEXT,league TEXT,player_id INTEGER,team_id INTEGER,award_name TEXT,notes TEXT);
CREATE TABLE IF NOT EXISTS championships(id INTEGER PRIMARY KEY,season INTEGER,competition TEXT,champion_team_id INTEGER,runner_up_team_id INTEGER,result_text TEXT,UNIQUE(season,competition));
CREATE TABLE IF NOT EXISTS raw_sources(id INTEGER PRIMARY KEY,url TEXT UNIQUE,sha256 TEXT,fetched_at TEXT,http_status INTEGER,local_path TEXT,bytes INTEGER,parser_version TEXT);
CREATE TABLE IF NOT EXISTS ingestion_log(id INTEGER PRIMARY KEY,run_started TEXT,run_finished TEXT,source_name TEXT,target_table TEXT,records_read INTEGER,records_inserted INTEGER,records_updated INTEGER,records_skipped INTEGER,status TEXT,message TEXT);
CREATE TABLE IF NOT EXISTS data_quality(id INTEGER PRIMARY KEY,checked_at TEXT,check_name TEXT,severity TEXT,table_name TEXT,issue_count INTEGER,details TEXT);
CREATE INDEX IF NOT EXISTS idx_games_date ON games(game_date);
CREATE INDEX IF NOT EXISTS idx_games_season ON games(season);
CREATE INDEX IF NOT EXISTS idx_games_teams ON games(home_team_id,away_team_id);
CREATE INDEX IF NOT EXISTS idx_events_game ON game_events(game_id);
CREATE INDEX IF NOT EXISTS idx_batting_player ON batting_game(player_id);
CREATE INDEX IF NOT EXISTS idx_pitching_player ON pitching_game(player_id);
CREATE INDEX IF NOT EXISTS idx_psb_player_season ON player_season_batting(player_id,season);
CREATE INDEX IF NOT EXISTS idx_psp_player_season ON player_season_pitching(player_id,season);
CREATE INDEX IF NOT EXISTS idx_players_name ON players(name);
CREATE VIRTUAL TABLE IF NOT EXISTS players_fts USING fts5(name,name_kana,content='players',content_rowid='id');
